---
title: "Formation Openrefine"
author: "Mathieu Saby"
site: bookdown::bookdown_site
documentclass: book
link-citations: yes
description: "Formation Openrefine du 28/09/2017, URFIST PACA"
output:
  bookdown::gitbook:
    css: style-perso.css
    split_by: chapter
    number_sections: false
    config:
      toolbar:
        position: static
      toc:
        collapse: subsection
        scroll_highlight: yes
        before: "<p><b>Cliquez sur un niveau pour déployer la table des matières</b></p>"
        after: null
    includes:
      after_body: js-perso.html
---
# Présentation {-}
Ce mini-site regroupe des supports de formations et de la documentation complémentaire concernant le logiciel [Openrefine](http://openrefine.org).

* Auteur : Mathieu Saby, BU de l'Université Nice Sophia-Antipolis (Email: <a href="mailto:mathieu(dot)saby(at)unice(dot)fr">nom.prenom@unice.fr</a> : Twitter : [27point7](https://twitter.com/27point7)
* Date de mise à jour : 28/09/2017
* Licence : à définir pour le site, mais chaque support de formation est assorti de sa propre licence.

OpenRefine est un outil libre destiné à nettoyer, transformer et enrichir des données.

    
Contenu du site : 

* [Formation longue à l'URFIST de Nice (28/09/2017)](#formation1)
* [Documentation](#documentation)
* [Ressources et liens utiles](#ressources)
* [Astuces de base pour Mac](#astuces-mac)



# Formation longue, URFIST de Nice {- #formation1}


Formation en 2x3h donnée à l'URFIST de Nice le 28/09/2017

* **[Matinée: Initiation à OpenRefine : nettoyer et préparer ses données](#p1)**
**Objectifs**
OpenRefine est un outil libre et gratuit potentiellement utile dans de nombreuses disciplines scientifiques et dans les métiers de l’information et de la documentation. Il permet de préparer le traitement de données tabulées hétérogènes, incomplètes, formatées de manière inconsistante, ou bien dont le format natif nécessite une transformation avant analyse.
Le logiciel propose une interface graphique permettant de garder une trace de chaque opération de nettoyage, découpage, regroupement ou enrichissement de données.
Aucune compétence en programmation n’est nécessaire pour maîtriser les fonctions de base, mais un langage spécifique permet de réaliser des opérations avancées.

**Programme**
- Intérêts respectifs d’OpenRefine et d’autres outils pour le nettoyage de données,
- Importer et exporter des données dans OpenRefine,
- Harmoniser des expressions présentant des variantes,
- Extraire des motifs (expressions régulières),
- Scinder des cellules contenant plusieurs valeurs,
- Enrichir un fichier en récupérant automatiquement des données sur le web,
- Croiser des fichiers,
- Si le timing le permet, introduction au langage GREL (spécifique d’Openrefine).


* **[Après-midi: OpenRefine: approfondissement](#p2)**
**Objectifs**
Cette formation permettra à un public connaissant déjà les fonctions de base d’OpenRefine de maîtriser les points suivants :
- Transformation avancée de données à l’aide de formules en langage GREL (spécifique d’Openrefine)
- Enrichissement de données à partir d’API ou de sites web
- Alignement de données avec des référentiels externes (Wikidata, Fichier d'autorité international virtuel…)

**Programme**
OpenRefine est un outil libre et gratuit potentiellement utile dans de nombreuses disciplines scientifiques et dans les métiers de l’information et de la documentation. Il permet de nettoyer, préparer, transformer et enrichir des données tabulées.
Dans les cas les plus simples, son utilisation ne nécessite aucune compétence informatique, mais les opérations avancées supposent l’écriture de formules dans un langage spécifique.
Cette formation permettra à un public connaissant déjà les fonctions de base d’OpenRefine de maîtriser les points suivants :
- Transformation avancée de données à l’aide de formules en langage GREL (spécifique d’Openrefine)
- Enrichissement de données à partir d’API ou de sites web
- Alignement de données avec des référentiels externes (Wikidata, Fichier d'autorité international virtuel…)
- Introduction aux expressions régulières
- Si le temps le permet, introduction à Jython (version de Python intégrée à Openrefine) et aux extensions (plug-ins étendant le comportement du logiciel)

## Première partie : intitation {- #p1}

* Diaporama 1: présentation générale
* Téléchargez les données pour suivre la démonstration : 
* Diaporama 2 : installatinon


## Exercice 1 {-}
Données bibliographiques (DOAJ)
* Téléchargez les données sur le bureau : 
* Créez un nouveau projet avec ces données dans OpenRefine

## Exercice 1 {-}
Données en open data (ville de Digne)
* Téléchargez les données sur le bureau : 
* Créez un nouveau projet avec ces données dans OpenRefine

## Exercice 3 {-}
Données en open data (ville de Digne)
* Téléchargez les données sur le bureau : 
* Créez un nouveau projet avec ces données dans OpenRefine


* Diaporama 2: installation
    * Démonstration
    * Exercice 1 :
    * Exercice 2 : 


## Fichiers de données {-}
* (data/rodents/Portal_rodents_19772002_scinameUUIDs.csv)

<https://msaby.github.io/formation_openrefine_2017_09_28/data/rodents/Portal_rodents_19772002_scinameUUIDs.csv>

[./data/rodents/Portal_rodents_19772002_scinameUUIDs.csv]

(./data/rodents/Portal_rodents_19772002_scinameUUIDs.csv)

(data/rodents/Portal_rodents_19772002_scinameUUIDs.csv)

<a href="data/rodents/Portal_rodents_19772002_scinameUUIDs.csv">data/rodents/Portal_rodents_19772002_scinameUUIDs.csv</a>

<https://ndownloader.figshare.com/files/7823341> : Portal_rodents_19772002_scinameUUIDs.csv
(cf https://data-lessons.github.io/OpenRefine-nhcdata-lesson/guide/)


# Deuxième partie : approfondissement {- #p2}
* Approfondissement du langage GREL
* Scraping
* Réconciliation
* Expressions régulières


Reprendre le fichier DOAJ


Fichiers Musiciens

Following the death of Amy Winehouse in 2011, the media declared that she was the latest member of the 27 Club, which consists of musicians who died at the age of 27. Commonly cited members of this club include Jim Morrison, Jimi Hendrix, Kurt Cobain, and Janis Joplin, which is hardly a representative sample (n=5) given the many thousands of musicians that are out there.

The spreadsheet File:Musicians.xlsx contains data sourced from Wikipedia about artists, their musical genres (one entry per row), and their birth and death dates. Multiple columns exist for birth and death dates as this data is semi-structured on Wikipedia and different techniques are needed to find these values.

The instructions in the tutorial above show step-by-step many types of functions that you will need to use when cleaning up the data. The instructions below show several of the formulas that you may find useful.

Create a new column named birthdate that uses the first value it encounters when scanning from birthdate1 to birthdate2 to birthdate3

forNonBlank(cells.birthdate1.value, v1, v1, forNonBlank(cells.birthdate2.value, v2, v2, forNonBlank(cells.birthdate3.value, v3, v3, null)))

create a new column named deathdate in the same fashion as with the birthdate column

forNonBlank(cells.deathdate1.value, v1, v1, forNonBlank(cells.deathdate2.value, v2, v2, forNonBlank(cells.deathdate3.value, v3, v3, null)))

Extract the year value for the birthdate and deathdate columns

value.match(/.*(\d{4}).*/)[0]

Create a new column showing the approximate age at which they died.

cells.deathdate.value - cells.birthdate.value

# Documentation {- #documentation}

## Installation {-}

Voir le site officiel d'OpenRefine : <http://openrefine.org>

* Fonctionne sous Windows, Mac, Linux
* Télécharger la dernière version (2.7)
* Installation: 
    * Mac : procédure classique : lancer l'installeur et déplacer le package dans le dossier Application
    * PC : dézipper dans le dossier où l'on souhaite installer (ex: Programmes)
    
## Lancement {-}

* Lancement du programme en tâche de fond
    * Mac : cliquer sur l'icône OpenRefine dans les Applications
    * PC : lancer openrefine.exe ou refine.bat
* Accéder à l'interface dans un navigateur (Chrome ou Firefox)
    * Si cela ne se fait pas automatiquement, ouvrir un navigateur (Chrome ou Firefox) et charger l'URL ***localhost:3333***

## Paramétrages (facultatifs) {-}

* Augmenter la mémoire maximale allouée au programme : par défaut OpenRefine ne peut utiliser plus de 1 Go de mémoire vive. Mais il est possible (et souvent utile) d'augmenter cette limite.
    * Mac : ouvrir le fichier `/Applications/OpenRefine.app/Contents/info.plist`,  modifier la valeur `<string>-Xmx1024</string>` (par ex: `<string>-Xmx2048</string>` pour doubler la mémoire maximale)
    * PC : ouvrir le fichier `refine.ini` et modifier la valeur `REFINE_MEMORY=1024`(par ex. `REFINE_MEMORY=2048`). Pour que cela soit pris en compte, il faudra **systématiquement** utiliser `refine.bat` et non `openrefine.exe` pour lancer le programme.

* Augmenter le nombre maximal de facettes
    * aller à l'URL <http://127.0.0.1:3333/preferences>
    * modifier la valeur de `ui.browsing.listFacet.limit`(2000 par défaut)


## Principales fonctions GREL et variables utilisables {-}
### Variables spéciales {-}
* value
* cell
* row
* record

### Fonctions GREL {-}

### Fonctions Python utiles {-}

## Détails sur l'utilisation des expressions régulières {-}

Les expressions régulières sont un outil informatique permettant de définir des motifs utilisables pour rechercher, modifier ou manipuler des chaînes de caractères. Elles sont implémentées dans différents langages informatiques et dans des outils comme Notepad++, Libreoffice, Word ou OpenRefine (mais pas Excel).
OpenRefine étant codé en Java, des particularités de Java se retrouvent dans la syntaxe des expressions régulières.

L'usage des expressions régulières est possible dans les transformations, les facettes et les filtres.

Informations adaptées du mémo d'Adriana Falcone : <http://arcadiafalcone.net/GoogleRefineCheatSheets.pdf>


cf https://msdn.microsoft.com/fr-fr/library/az24scfc(v=vs.110).aspx
https://www.javacodegeeks.com/2012/11/java-regular-expression-tutorial-with-examples.html


Expression régulière|Description
---|-------------------------------------------------------------------------------------
.|n'importe quel caractère
^abc|"abc" au début d'une ligne
abc$|"abc" à la fin d'une ligne
[abc]|"a" ou "b" ou "c" (on parle de classe de caractères)
[^abc]|n'importe quel caractère sauf "a", "b" ou "c"
[abc][19]|"a" ou "b" ou "c", suivi de "1" ou "9"
[e-j]|"e" ou "f" ou "g" ou "h" ou "i" ou "j"
[B-E]|"B" ou "C" ou "D" ou "E"
[2-5]|"2" ou "3" ou "4" ou "5"
[2-4abe-g]|"2" ou "3" ou "4" ou "a" ou "b" ou "e", "f" ou "g"
abc|"abc"
abc\|def|"abc" ou "def"
(abc)|"abc" (les parenthèses sont utiles pour appliquer un quantifieur sur la chaîne)
(abc\|def)|"abc" ou "def"


Métacaractères (lettres précédées de /\)

Expression régulière|Description
---|-------------------------------------------------------------------------------------
/\d|chiffre: raccourci pour [0-9]
/\D|tout sauf un chiffre: raccourci pour [^0-9]
/\s|caractère "blanc" (espace, tabulation, saut de ligne...: [/\t/\n/\x0B/\f/\r] )
/\S|tout sauf un caractère "blanc" (inverse de /\s)
/\w|caractère utilisé dans un "mot":[a-zA-Z0-9_] (attention, ne comprend pas les caractères accentués ou non latins)
/\W|tout sauf caractère utilisé dans un "mot" : [^a-zA-Z0-9_] (attention, comprend les caractères accentués ou non latins)
/\b|limite d'un "mot" (d'une séquence de caractères de type /\w )
/\B|tout ce qui n'est pas limite de "mot

Quantifieurs
Les quantifieurs indiquent le nombre d'occurence d'un caractère ou d'un groupe de caractère qui doivent être présents pour que la chaîne corresponde à l'expression régulière.

Expression régulière|Description
---|-------------------------------------------------------------------------------------
X?|X présent 0 fois ou 1 fois
X*|X présent 0 fois, 1 fois ou plus
X+|X présent 1 ou plus
X{n}|X présent exactement n fois
X{n,}|X présent n fois ou plus
X{n,m}|X présent au moins n fois et au plus m fois

Ici X peut désigner un caractère isolé, une classe de caractère regroupés par des [], ou une suite de caractères regroupés par des ().

Ex : 1?[abc]+(yz|io)* peut correspondre à 1abc, 1abcio, 1abcyz, 1abcabcabc, 1abcabcabcabcyzyzyzyzyz, abcabcyzioio, etc

Pour utiliser les caractères spéciaux comme des caractères ordinaires, il faut les précéder d'un /\.
Ex : /\* = astérisque
Ex : /\? = point d'interrogation
Ex : /\[ = crochet ouvrant
Ex : /\. = point
Ex : /\/\d = caractère /\ suivi de la lettre d 

## Détails sur les algorithmes de clusterisation {-}

cf. <https://github.com/OpenRefine/OpenRefine/wiki/Clustering-In-Depth>
Dans l'ordre d'agressivité croissant :

### Collision de clés
Méthodes les plus rapides, mais les plus simples : création d'une "clé" synthétisant la valeur de chaque cellule ciblée, puis comparaison des clés.

#### Empreinte (Fingerprint)
Regroupe des expressions ne différant que par la casse, les signes diacritiques, la position des mots, le redoublement des mots, le nombre d'espaces, la ponctuation.
Donc auront la même empreinte : "ecole, france", " france ecole", "ECOLE : FRANCE  ecoLE", "ec:ole fra:nce", "ec-ole france"
Normalement cela devrait aussi fonctionner avec : "école france", " france Ecole", "éCOLE FRANCE  ecoLE", mais en réalité les diacritiques sont mal gérés (bug signalé)
Attention, faux amis possibles (ex: "élève" et "élevé" seront regroupés...)

#### Empreinte Ngram (Ngram Fingerprint)
Même principe mais permet de jouer sur la taille des paquets de lettres utilisés lors de la comparaison (utiliser la valeur 1 ou 2)
Ex : "Krzysztof", "Kryzysztof" et "Krzystof" ont la même empreinte ngram avec le paramètre 1.

### Modèles phonétiques
Utiles pour rapprocher des noms propres mal saisis. Mais ne fonctionne pas bien pour le français (Metaphone 3 fonctionne  sur l'anglais et Cologne-phonetics sur l'allemand)

## Plus proche voisin (Nearest neighbour)
La "taille des blocs" (6 par défaut) est un paramètre permettant de limiter le coût de calcul, mais qui a l'inconvénient de réduire l'efficacité. A baisser jusqu'à 1 si nécessaire.

### Distance de Levenshtein {-}
Basé sur le nombre d'opérations élémentaires nécessaires (suppression, ajout, substitution de caractère) pour passer d'un mot à un autre. Les variantes d'un même caractère (casse, diacritique) sont considérés comme différents.
Ex : roi -> loi : distance = 1
Ex : roi -> loir : distance = 2
Ex : roi -> ROI : distance = 3
Ex : roi -> rôti : distance = 2
Le "rayon" définit la distance maximale recherchée (plus il augmente et moins l'opération sera stricte).

### PPM {-}
Méthode basée sur la complexité algorithmique, utilisé surtout pour comparer les séquences ADN

## Recettes (Comment faire pour...) {-}
### Créer une facette basée sur le N-ième caractère des cellules {-}
* Première lettre
* Dernière lettre
* Nième lettre

### Créer une facette basée sur une séquence de caractères {-}
* Découpage : position 
* Recherche de la séquence
* Recherche de motif

### Créer une facette basée sur la comparaison de deux colonnes {-}
### Repérer les lignes complètement vides {-}

### Créer une colonne basée sur une facette {-}
### Compter les occurrences de chaque caractère dans une cellule {-}
### Compter les occurrences de chaque caractère dans une colonne {-}
split (//)
### Compter les occurrence d'un texte dans une colonne {-}
### Chercher les valeurs uniques d'une liste {-}
### Supprimer ou conserver certaines valeurs d'une liste {-}
### Manipuler des "enregistrements" (records) {-}
### Compter

### Comparer une chaîne de caractères à un motif avec les expressions régulières {-}
* NOM, Prénom
* Numéro de téléphone
* E-mail
* URL

### Extraire un motif avec les expressions régulières {-}
* Nom à partir de *NOM, Prénom*
* Prénom à partir de *NOM, Prénom*
* Extension à partir d'une adresse E-mail
* Extension à partir d'une URL
* Début d'un numéro de téléphone

### Convertir des valeurs de type chaîne en valeur de type date {-}
Les chaînes contenant des dates formatées selon la norme ISO 8601 peuvent être transformées directement en valeur de type date avec la fonction `toDate`
Ex: 2010
Ex: 2010-05 (mai 2010)
Ex: 2010-05-31 (31 mai 2010)
Ex: 2010-05-31T01:10:05Z (31 mai 2010, à 1h10m05, en temps universel)

### Passer une chaîne en majuscules
* toUppercase (string s)
Ex : "écolEs françaises".toUppercase --> "ÉCOLES FRANÇAISES"

### Passer une chaîne en minuscules
* toLowercase (string s)
Ex : "ÉcolEs fraNçaises".toUppercase --> "écoles françaises"

### Passer une chaîne en *Titlecase*
* toLowercase (string s)
Ex : "écolEs françaises".toUppercase --> "Écoles Françaises"


### Supprimer un suffixe donné d'une chaîne
* `value.chomp (string *suffixe*)`
Ex : "cheval".chomp("val") -> "che"


* 02-12-2009 -> 2009 
`value.slice
* AAAA-MM-JJ -> JJ-MM-AAAA
* JJ:MM AA ->   JJ-MM-AAAA

### éliminer les diacritiques

### éliminer les caractères non alphabétiques

### éliminer des caractères spéciaux
ex: espace insécable codé en HTML par &nbsp; et codé par &#160;
* split(escape(value,'xml'),"&#160")[0]
Explication : 


### éliminer des espaces
* espaces initiaux et finaux : `value.trim()`
* espaces finaux : 
* espaces au milieu



### Aspirer un site {-}
### Réconcilier {-}
### Extraire des informations à partir de données JSON dans une colonne {-}
* Parser
* Jython

### Extraire des informations à partir de données XML dans une colonne {-}
### Extraire des informations à partir de données HTML dans une colonne {-}
* Nettoyer le HTML
* Parser

### Utiliser un template pour l'export {-}


# Ressources et liens utiles {- #ressources}
## Guides et tutoriels
* David Huyn (2011), [Google Refine](http://davidhuynh.net/spaces/nicar2011/tutorial.pdf)
*Version datée du logiciel, mais présentée par son créateur*
* Chris David (2012-2016), http://enipedia.tudelft.nl/wiki/OpenRefine_Tutorial
* Jeff Moon (2015), [OpenRefine](https://accoleds.files.wordpress.com/2015/12/accoleds2015-open_refine.pdf)
*Présentation pour un consortium de bibliothèques canadien*
* INRA (2016), [OpenRefine](http://wiki.inra.fr/wiki/traitementsdocumentaires/Main/OpenRefine)
* Free your metatdata [U. Ghent et Bruxelles] (2011-2016), <http://freeyourmetadata.org/>
* Programming historian
* Data carpentry
    * Ecologie
* Library carpenty
* Thomas Padilla
* John Little
* Courtin?

## Astuces et retours d'expérience
* Kuali OLE (2014-2017), [OpenRefine How-Tos](https://openlibraryenvironment.atlassian.net/wiki/spaces/OLE/pages/655671/OpenRefine+How-Tos)
*Recettes utilisées dans le cadre le projet Kuali OLE pour manipuler des données bibliographiques (KBART). Certaines supposent l'utilisation d'une extension*
* Bibliopedia
* Blog bib
* Courtin
* Mémoire et aieux
* Punktonomo
* Bases de question sur Stack Overflow
* Groupe Google
* [RefinePro Knowledge Base for OpenRefine](http://kb.refinepro.com/) (2011-2015)
**Base de connaissance, nombreuses astuces**
* Tony Hirst, [OUseful.info, the blog...] https://blog.ouseful.info/
**Nombreux billets sur openrefine**

OSEFUL
Etore rizza




Icône utilisateur
Kristin Antelman

* Doc officielle
* Stackoverflow
* Groupe Google (consultation libre)
* Tutos
* Blog 'Open Refine for Librarians' http://liwong.blogspot.fr/
* OSFUL
* Riza 
* Courtin

* OpenRefine : exemples <https://www.bibliopedia.fr/wiki/OpenRefine_:_exemples>
Exemple de recettes utilisées en bibliothèque

Utilisation d'API (ABES, Crossref...)
Extraire des données d'une page web
Vérification d'un chantier de recotation
Vérification du dépôt d'articles dans HAL en fonction des couleurs RoMEO à partir du WoS
Nettoyage de données fournies par des éditeurs (GOKb ; ABES)





# Astuces de base pour Mac {- #astuces-mac} 
**Pour réaliser** | **Opération**
--- | ---
Clic droit | soit [Ctrl] + clic, soit clic avec deux doigts
Symbole dessiné en bas d'une touche | [Shift]+ touche
\\ | [Alt]+[Shift] + /
[ | [Alt]+[Shift] + 5
] | [Alt]+[Shift] + °
{ | [Alt] + 5
{ | [Alt] + °
\| | [Alt]+[Shift] + l
~ | [Alt]+ n
Copier | [Cmd] + C
Couper | [Cmd] + X
Coller | [Cmd] + V




